// Downloads the site's Google Fonts (latin subset, woff2) into public/fonts/
// and writes src/styles/fonts.css, so no third-party font requests happen at
// runtime. Re-run with `npm run fonts` if the font set changes.

import fs from 'node:fs';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=DM+Sans:wght@300;400;500;600&display=swap';

// A modern UA makes Google serve woff2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const fontsDir = path.resolve('public/fonts');
const cssOut = path.resolve('src/styles/fonts.css');
fs.mkdirSync(fontsDir, { recursive: true });

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Failed to fetch font CSS: ${res.status}`);
const css = await res.text();

// Blocks look like: /* latin */ @font-face { ... }
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
const faces = [];
let m;
while ((m = blockRe.exec(css)) !== null) {
  const [, subset, body] = m;
  if (subset !== 'latin') continue;
  const family = body.match(/font-family:\s*'([^']+)'/)[1];
  const style = body.match(/font-style:\s*(\w+)/)[1];
  const weight = body.match(/font-weight:\s*(\d+)/)[1];
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)[1];
  const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)[1];
  faces.push({ family, style, weight, url, unicodeRange });
}

if (faces.length === 0) throw new Error('No latin @font-face blocks parsed.');

const slug = (s) => s.toLowerCase().replace(/\s+/g, '-');
let out = '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n';

for (const f of faces) {
  const file = `${slug(f.family)}-${f.weight}${f.style === 'italic' ? '-italic' : ''}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  fs.writeFileSync(path.join(fontsDir, file), buf);
  console.log(`✓ ${file} (${(buf.length / 1024).toFixed(1)} KB)`);
  out += `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}
`;
}

fs.writeFileSync(cssOut, out);
console.log(`✓ wrote ${path.relative(process.cwd(), cssOut)} with ${faces.length} faces`);
